// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: app/pkg/common/proto/id.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pkg_common_proto_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_pkg_common_proto_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_pkg_common_proto_id_proto_rawDescGZIP(), []int{0}
}

type CreateIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateIdResponse) Reset() {
	*x = CreateIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pkg_common_proto_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIdResponse) ProtoMessage() {}

func (x *CreateIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_pkg_common_proto_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIdResponse.ProtoReflect.Descriptor instead.
func (*CreateIdResponse) Descriptor() ([]byte, []int) {
	return file_app_pkg_common_proto_id_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_app_pkg_common_proto_id_proto protoreflect.FileDescriptor

var file_app_pkg_common_proto_id_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x22, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x32, 0x38, 0x0a, 0x09, 0x49, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x09, 0x2e, 0x69, 0x64, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x14, 0x2e, 0x69, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_pkg_common_proto_id_proto_rawDescOnce sync.Once
	file_app_pkg_common_proto_id_proto_rawDescData = file_app_pkg_common_proto_id_proto_rawDesc
)

func file_app_pkg_common_proto_id_proto_rawDescGZIP() []byte {
	file_app_pkg_common_proto_id_proto_rawDescOnce.Do(func() {
		file_app_pkg_common_proto_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_pkg_common_proto_id_proto_rawDescData)
	})
	return file_app_pkg_common_proto_id_proto_rawDescData
}

var file_app_pkg_common_proto_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_pkg_common_proto_id_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: id.Empty
	(*CreateIdResponse)(nil), // 1: id.CreateIdResponse
}
var file_app_pkg_common_proto_id_proto_depIdxs = []int32{
	0, // 0: id.IdService.Create:input_type -> id.Empty
	1, // 1: id.IdService.Create:output_type -> id.CreateIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_pkg_common_proto_id_proto_init() }
func file_app_pkg_common_proto_id_proto_init() {
	if File_app_pkg_common_proto_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_pkg_common_proto_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pkg_common_proto_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_pkg_common_proto_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_pkg_common_proto_id_proto_goTypes,
		DependencyIndexes: file_app_pkg_common_proto_id_proto_depIdxs,
		MessageInfos:      file_app_pkg_common_proto_id_proto_msgTypes,
	}.Build()
	File_app_pkg_common_proto_id_proto = out.File
	file_app_pkg_common_proto_id_proto_rawDesc = nil
	file_app_pkg_common_proto_id_proto_goTypes = nil
	file_app_pkg_common_proto_id_proto_depIdxs = nil
}
