version: "3.9"

services:
  id-manager:
    image: vertisan/vrsf-playground-id-manager:latest
    environment:
      - GIN_MODE=release
      - SERVICE_NAME=id_manager
      - PORT=80
    networks:
      - vrsf-playground-network

networks:
  vrsf-playground-network:
    name: vrsf-playground-network
    driver: bridge
