version: "3.9"

services:
  id-manager:
    image: vertisan/vrsf-playground-id-manager:latest
    environment:
      - GRPC_PORT
    networks:
      - vrsf-playground-network

networks:
  vrsf-playground-network:
    name: vrsf-playground-network
    driver: bridge
